services:
  dbj:
    image: idbj
    build:
      context: ./data/
      dockerfile: Dockerfile
    container_name: mysql-server-java
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=develop
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - j-network

  webj:
    image: iwebj
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-web-java
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://dbj:3306/develop
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - 8080:8080
    depends_on:
      - dbj
    links:
      - dbj
    networks:
      - j-network

networks:
  j-network:
    driver: bridge

volumes:
  db_data:
